#----------------------------------------------------------------------
# This file was generated by C:\Program Files\Python37\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

boxsliced24 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA'
    b'AAIkSURBVEiJrdYxSJVRFAfwn4FRQQaKBRqBg0Fa1BBIS0kFDeHg4BRILkGThpND4NggYlvh'
    b'Ji0VToEINdRkuFQWRkFRSFRDWUpFYb6G73y8+/T5TPEPB+537v/8773nnHv52Biqw7Yc29CD'
    b'j2E94dsSnMA0CitsOuY2jUbcwnIIzuFC2Fz4loPTuBHh7ejFQoj8xnXsTji7MIifwfkR3zvX'
    b'E+/AW8U03ENTBf5+jCk9ZTeqypGnEuFnaF9vNwnaIyaPn8on0k5YSMY1qNvAAnURU06rBKfw'
    b'NNnJQxytIHwIkwl/FufWIrfgcuykG58j6K8sz3sTbq2s8EvB+SJrjD2h0VJugbtB/hAL1GIE'
    b'f8L/NUR6Y1yIuZHgdkdsIbRWoVVpoR+jrUwacpuMubbgpgVuXStNVejCe8WLdAcHZC38MqwD'
    b'DbgZKcxPfkmFJ+QaFnFV1hWD+KX0Iu1QvIjflV7EfRG7GFqrMJAc812cpAnjif9NWP49Hpyu'
    b'iMn9A2udYmU+8zqcxkzinwnfMTxK/E9wci3xTtzGcVlHfFLapg24GFavfJseD43OcguMJYKj'
    b'aMawYpvO40rYvGKbDgd3VLHgY+UWqMGQrGgFfEM/jmDC6jadiLn+4OYFH1L6bKxCs6w1c6HX'
    b'siKelz0FszE+ixcJ774K/V8OZ/A8EXiAwzgoe8Zz/6tYcFOoRp/SnKc16bNFPwH1uCHrmqUY'
    b'12+F8Eo0h/03/gH3GcvLLWNXGgAAAABJRU5ErkJggg==')

boxsliced24_disabled = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA'
    b'AAQASURBVEiJnVVdaBxVGD3nzqwktYZG0T4YBAuBNlaDTaTpZjYRBH3Rh4IWEUUKRZCWbiq2'
    b'FlqpaVFaY0wiWBT6oqL4IPXFWgoK7s7e/JCtqGWNVEEo1geFxFZott2Ze3zoXUmaxCZeGJi5'
    b'93zn3O98H/MBK1jlcjlTLpczK4kxywFJMtba7dVq9UK1Wr1grd0uaVmxvBnAWrtF0giAh244'
    b'miSZ7+7uHvtfAqOjo3c7544BeAYAJf1Gcj8ASDpKsgWAAHxijHklm81eXJZApVK5ZXp6+kWS'
    b'RwDcBuCapPdIHoyi6G8AKJfLq2ZnZ/eR3AegEcAVSQNBEBzLZrOzSwrEcfwEyREA9wIAyS+S'
    b'JNnd29v762K3Gx8fb0nT9A1Jz9azBHAgiqKPSGqeQKlUGgPQ5T9/kJTP5XLfLGXhDRd72F/s'
    b'gbp2FEVbgPlddHnOe5Mx5o7lkAOAxzYtxjXPomKx2GuMGQHQDgAkC865fC6X+34x4rGxsQ1J'
    b'kgyRfAwAJE0FQbAnm82e+Vd8DnlbEARtYRj2SHoewB+Sekl+a6390Fp7Vx07Ojp6exzHI2ma'
    b'nvPk05L6qtXqFknrisVi2wIBkv2SjidJMuXT3uB9TSU9J+mnOI7zcRznnXO/kNwNwJEcMca0'
    b'AphpbGz8UdJxkv113nCOwGsAWgB0kfzAOTchKR+G4ft1G0gO1/GSzoRhuCdJkiaSX5Lc7I/G'
    b'PdfCGkhiqVR6kuRbAO4BIJKfSXpZUjvJNz1uH8mzJA9J2uGd+F1SfxRFJ0i6BRZZa49aay+T'
    b'XJ/JZDZJ6gdwVdJTAKYAdNRqtQebm5vbAawDMCXpBQCJpHfCMNxEcq219pK19ugCAUmXAKwG'
    b'cLhWq50FUEnTtA3ASQCrSB7KZDKVmZmZKW9VE4CTaZquB1BKkmQCwGEAqz3XQoviON7sC1v3'
    b'c0JS3hhzq6RhAPf7/XMk+3C9e0YA9Pj97/wPsLhAII7jrSSfBjAgqc37vRbXO+VjSftJPgoA'
    b'aZqeInmQ5E4AgRc6TNIC2Cvp01wu9/k8i4wxWwFsAzBBMpemaQ7AEHybAqhIapbUbIw5X29T'
    b'AENpmnaR3AhgAsA2zzW/BkEQ7CI5CCABsCMIgklJF40xHQBOA1gD4G3/rAFw2hjTIeliEAST'
    b'AHYASEgOBkGwa9EaAEChUGgNw/B13z0g+bNz7oAx5opzbsBnu9c5d9UX+z4f+hWAviiKKnP5'
    b'lhw4xWLxEWPMMICNACDpa2NMn3PumjFmUNLjHnqe5Evd3d2nFuP5z5FZLpcz1Wp1J4BD3paa'
    b'P8oA+AtAf0NDw7udnZ21pThuOpN9NncaY47gus8AcMI592pPT8+fy4lf9ioUCq2FQqF1JTH/'
    b'ABF15ps8rND+AAAAAElFTkSuQmCC')
