#----------------------------------------------------------------------
# This file was generated by C:\Program Files\Python37\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

image24 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA'
    b'AADgSURBVEiJ3ZU7EoIwEEDfWMgJzFjJPdQbeDCFI6lHsJLCE8ABxMYKC5cxMEuICY3uzA6f'
    b'LO/BkkngnyIBcqACmsCsgAyYa4I8AtzPgyZo33wd1gAANsIotcHWHhsdzsxRmAJn4AGc5Ho6'
    b's8Dtvh4DOYMDNZ9/0gD3qQVjX2CAi6QJEaQCreW46sEL65nCkngLhsKGF71zEytYAFepuwFL'
    b'5V6wQINrY0GCflvMSM1XAh+4XfuVwNWWofAWhMC9BaFwp6BdrncR8C2O5TqjO81icq8JEpE8'
    b'I8Al791M3TJ/M17S/r2u/ykcqQAAAABJRU5ErkJggg==')

image24_disabled = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA'
    b'AAHSSURBVEiJ1ZOxbhNBEIb/GceiQLJkS1gKDW0kJ1UKIi86dLpAAa8AFXmFRDRAQQWvgGjI'
    b'KyA3YCROt4TUSUFLE0dJY8lUsdifIrtwHHeR70IB09xq9vb7Zmd3gf89JAxGo9GVTqfzHMAD'
    b'AMsNeROSu71e78lgMDgDgKUw4+Hbl6kWwLKI7EynUwJ4/JsA55VDVc1wOPzUhJ6mqVHVjOTD'
    b'INC8HQCawgEgiiLrh9dDbqniX1hrbzjnXovIBoA9EdkyxnytK9WqCQ9PAFwFsEnyVV34hQIR'
    b'uQmcn4lPbTQRVLaI5L6IJM650NfP+XlrbZ/kyBdzzxhzUsap3IGqPgLwDsA3/90qwMcA1gGs'
    b'kxxba/u1duAP9G4xn4OvAjj06VUvSUguJiiLNE2vkXzv4V/m8/mdVqv1XVXHANZIfiyuqWxR'
    b'GTyAPDyO4/g4iqJT51wC4ADASiOBtbavqh88/FBEbsdxfBzmoyg6FZFN/GrZ4oJiz0UkKbsx'
    b'xpgT/24WF5T1vOo6BsnCgqqeX1RQWZQK/ha8KJh4+P2m8CzLbvnhUcj9fAckd0VkR1Xf5tas'
    b'tNvtSZZldQt/88cOZrPZU5IvAZzVpeXiSERedLvdZ5dg/GPxAwuc01dHjDwYAAAAAElFTkSu'
    b'QmCC')
