#----------------------------------------------------------------------
# This file was generated by C:\Program Files\Python37\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

play24 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA'
    b'AAC/SURBVEiJ3dWhqkJBEMbxn8dgusVgtthMVp9AzL6Cr+Ar2E2+gk9gFERst9wn0HjDDYJB'
    b'QY7BPXAw3bCD6AfLMjvD/GF3Z4ZP1BY/GEYByrRuWOArCnBJ+xHjCEAf+5q9QicnAApMcUpn'
    b'f8lu5AJU6mJd823QywmoNMFv8p8xQzMnANpY1uK+McgJqDTCIcVeMUcrJ4BHjSw8aqbE7jmg'
    b'+GeirHr5FYU+ctg37QoqtNBWEd7swtt12MAJH5nvpTvvwl6shFAYTgAAAABJRU5ErkJggg==')

play24_disabled = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA'
    b'AAHYSURBVEiJ1ZVLaxNRGIafb6YoCAF14aIguBEEL6AimJxMAm68resvqK1C9y3+ASu4FNH2'
    b'H6TbGnGjJDMnKYiXRYWCG1HIQkEXAVeTeV002USb5uaiz2rmm3Peh+8czhk46Fh/IUmSGDia'
    b'Zdm9Uqnk/4dA3ccMeAo8KBaL7XEFwYBvKbAEfPLe3566wMwuA1vASUmb3vuK9/7E1ATOuW3n'
    b'nJO0CLQlzUnaieN4QdJfSzuyAMDMsiiK1sIwvCDpFXDMzJ43Go03tVrt9MSCHvl8/ksURTck'
    b'3QF+SCqHYfgxjuPlSqUSTizoEUXRRhAEZ8xsDThiZquzs7Nv6/X6pakIAAqFwk/n3CJwC/gK'
    b'XAyCYMt7v1qtVg9PLOhRLBZfAueAJ0AoaTmXy72emmBYxhYkSXIT2Gb3MHbM7FG73b7WP25m'
    b'1OBGo3Fc0kNJC93ShyzL5kul0vt/jR+pgziO57Is2+mG/5a00mq1ruwVDkN20Gw2T6Vp+szM'
    b'rgOYWS1N07vlcvnzfnMHCiQFSZLMdzqdx2aWA35JWnHOrZuZBs3tsed1bWbnJa0DV7vvG8CS'
    b'c+77MMH7diDpHXAI+GZm951zL0YJ7jFok2fYPURnxw3vhfSTMMVf5sHnD9i2wwb8t1C4AAAA'
    b'AElFTkSuQmCC')
