#----------------------------------------------------------------------
# This file was generated by C:\Program Files\Python37\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

plussquare24 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA'
    b'AACZSURBVEiJ7ZVtCoQgEIYfIupOW/fr41rtVbRj1I9GqGWI1THYlh4YBEfeV0dx4J+ogRHw'
    b'wJIYHhiASjMYDcKf0WsGYeevtAIA0IiG05LB3cpBp8ggeEqswSSRxDclil7zcyXKbjBxfN+B'
    b'/dzpnVx+gj3PJauUkevfFrP7/0WzjI1Br5XRa8mBfA2n0wxqMXEGYcfWzdSWeU9WH0NsB9xp'
    b'Sf0AAAAASUVORK5CYII=')

