#----------------------------------------------------------------------
# This file was generated by C:\Program Files\Python37\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

box24 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA'
    b'AAFbSURBVEiJzZWxTgJBEIa/A6Q/En0GSUx8AOwoDbGg9wUsaHwBWizA+AY8AzFUxoIHUAtj'
    b'SNTahDO0Ggw2s2HY7C7LnRr/ZHJ7O//8/93eZQb+CXaBPvAs0Ze9wqgC58AcWFoxl1w1r/gJ'
    b'MFWCI+BAYqT2p8KNRh24VgJPwLGD1wTuFe8GOAwJJ8AFsJCCGXAGVAI1FeHMpGYhGomLPFGk'
    b'KyANPY2FVGrMw01cpIzV674C7S0M2lJj6jMXySTv1PqW8LnWgbHiP6q116AEnAJvcv8FDIE9'
    b'xa0Bl6yOJAM6QDnGwCAFBsCn7L+LSEfWS8kNWP9e0QYG9jGYGEsuVsefELQUpxXg5TbIxSlt'
    b'IBfGnxq8yLVRQO/I0lpDF/+vZ+D7BvYv3XUZJECPcLOzDVzNroen2Rns42/X2qAJPKi9je3a'
    b'hmvguNZbDxyNXx2ZGmbof0j82NC3sSMRjW8u95wsqP+yZQAAAABJRU5ErkJggg==')

box24_disabled = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA'
    b'AAK9SURBVEiJvZXBSxRRHMe/v7czXWOVOnfpIKsFeZKZ2Vg9WGj6F0THSCS0yCAiMSKIJbOQ'
    b'wqt09JKyVIfamDfPuWyCqEgEXYXCdru2M+/XobeyO7m2a9j39OP73u/ze7+ZefMDjljUyibf'
    b'908IIe4AGDHWstb6YTab/fZPBba2to6Vy+XrAO4COJ5Y/gHgQTqdfpbJZH42Y4hmC0qp0Uql'
    b'sgkgb+AFIuohoh4ABePlK5XKplJqtOUOwjDsiuP4MYCLxvpERDcdxynU7/N9f0AIMQvgjLGK'
    b'zDzped76vh0wMwVBkI/jeMPAd5l5vFqtdifhAJDNZt9Vq9VeZh4HsAsgR0QfgyDIM/PewfcC'
    b'KWVARA6AWAjxIo7je57nlZu1Xi8pZTqVSt3XWl8DkGJm5Xme29CBEKLLhCmt9bAQor8VuMnt'
    b'11oPA0glWA2PqMOE6wBOMfOSUuqDlPJsM3AYhl1SyjfMvGRythOsP78ix3HOMfMVAF+Z+TwR'
    b'rSmlFpVSJ2t7VldXO6SUT+M43iCiQQDfmXliZ2enJ8mzkgYRaQCLUsoVIcQ0M48x82UAw1LK'
    b'GQDQWk8TURpAlYjmtdYztfcVBMHBBWoyCRNhGC5EUfSEiAaJaK62zsxvLcua7Ovr227GOLBA'
    b'TQZwQUp5iYiWDXzE87yVv+UCB9zkpOqBrcLbKnBY/dcCXwDA933nsLAgCNx6VrLASwAQQhSV'
    b'UnNSynSrYCllWik1B+B9PQuo+xcxMymlHgG4gd9XfpeZp6MoWsjlcpE5IQOA67oEAMVi0bIs'
    b'6yoRzQDoBBADmHUc5zYRcUMHRMSu604JIboBvAbQSUTztm1vKqWGkqf2fX/Atu01Ipo38CIz'
    b'97quO1WDN3SQlBkieWY+bawCgKFkTESfAdxyHOfVfpwjH5ntDv0xYz1vdei3pVKpZJdKJbud'
    b'nF/bxkrD2LHtkgAAAABJRU5ErkJggg==')
