#----------------------------------------------------------------------
# This file was generated by C:\Program Files\Python37\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

box = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA'
    b'AAFbSURBVEiJzZWxTgJBEIa/A6Q/En0GSUx8AOwoDbGg9wUsaHwBWizA+AY8AzFUxoIHUAtj'
    b'SNTahDO0Ggw2s2HY7C7LnRr/ZHJ7O//8/93eZQb+CXaBPvAs0Ze9wqgC58AcWFoxl1w1r/gJ'
    b'MFWCI+BAYqT2p8KNRh24VgJPwLGD1wTuFe8GOAwJJ8AFsJCCGXAGVAI1FeHMpGYhGomLPFGk'
    b'KyANPY2FVGrMw01cpIzV674C7S0M2lJj6jMXySTv1PqW8LnWgbHiP6q116AEnAJvcv8FDIE9'
    b'xa0Bl6yOJAM6QDnGwCAFBsCn7L+LSEfWS8kNWP9e0QYG9jGYGEsuVsefELQUpxXg5TbIxSlt'
    b'IBfGnxq8yLVRQO/I0lpDF/+vZ+D7BvYv3XUZJECPcLOzDVzNroen2Rns42/X2qAJPKi9je3a'
    b'hmvguNZbDxyNXx2ZGmbof0j82NC3sSMRjW8u95wsqP+yZQAAAABJRU5ErkJggg==')

