#----------------------------------------------------------------------
# This file was generated by C:\Program Files\Python37\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

boxsliced24 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA'
    b'AAIkSURBVEiJrdYxSJVRFAfwn4FRQQaKBRqBg0Fa1BBIS0kFDeHg4BRILkGThpND4NggYlvh'
    b'Ji0VToEINdRkuFQWRkFRSFRDWUpFYb6G73y8+/T5TPEPB+537v/8773nnHv52Biqw7Yc29CD'
    b'j2E94dsSnMA0CitsOuY2jUbcwnIIzuFC2Fz4loPTuBHh7ejFQoj8xnXsTji7MIifwfkR3zvX'
    b'E+/AW8U03ENTBf5+jCk9ZTeqypGnEuFnaF9vNwnaIyaPn8on0k5YSMY1qNvAAnURU06rBKfw'
    b'NNnJQxytIHwIkwl/FufWIrfgcuykG58j6K8sz3sTbq2s8EvB+SJrjD2h0VJugbtB/hAL1GIE'
    b'f8L/NUR6Y1yIuZHgdkdsIbRWoVVpoR+jrUwacpuMubbgpgVuXStNVejCe8WLdAcHZC38MqwD'
    b'DbgZKcxPfkmFJ+QaFnFV1hWD+KX0Iu1QvIjflV7EfRG7GFqrMJAc812cpAnjif9NWP49Hpyu'
    b'iMn9A2udYmU+8zqcxkzinwnfMTxK/E9wci3xTtzGcVlHfFLapg24GFavfJseD43OcguMJYKj'
    b'aMawYpvO40rYvGKbDgd3VLHgY+UWqMGQrGgFfEM/jmDC6jadiLn+4OYFH1L6bKxCs6w1c6HX'
    b'siKelz0FszE+ixcJ774K/V8OZ/A8EXiAwzgoe8Zz/6tYcFOoRp/SnKc16bNFPwH1uCHrmqUY'
    b'12+F8Eo0h/03/gH3GcvLLWNXGgAAAABJRU5ErkJggg==')

