#----------------------------------------------------------------------
# This file was generated by C:\Program Files\Python37\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

boxtop24 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA'
    b'AAFeSURBVEiJzZW9SgNBFIW/idHewncwlQ+gnaWE+AS+gIWN2NtqkeAL+BIiqaysg1ioBBRB'
    b'UIQIIULAsMla7B28+zP7MyvigUuWuWe/MySTufBPtAZ0gUfgGTiTtdpaAQ6BMRACoZECpsCR'
    b'eLzUAYYK/GlUgAp6BXargFvAZRE4I2gAbOSBDXAKBAKeGpiVgataAOfCSuladj03MKkI1gGh'
    b'sFL6wA8amuhkvdmvVVgp2eZNhaAJcK/evVPPzoAGsAe85wQtTAQO1I4PgKUyAVarQA+YSdBc'
    b'4C9EOw+l1xOvi1PYaAF91bfVl15ZjrshaitPO8fnHeDlaRSYa+tPA57kc7MGbyvBiukY99Gz'
    b'cv0GsSMtrJQMcMLPn2cE7APNnICmeEayHggj87KzWkdd18ADsJMRsA3cqrUrCq7rpGIDB7hw'
    b'PA/F66XUyFQ1lp73yNSyQ/9LqssvDf2klqVK6xvhrdNKp5HWMwAAAABJRU5ErkJggg==')

