#----------------------------------------------------------------------
# This file was generated by C:\Program Files\Python37\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

boxtop24 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA'
    b'AAFeSURBVEiJzZW9SgNBFIW/idHewncwlQ+gnaWE+AS+gIWN2NtqkeAL+BIiqaysg1ioBBRB'
    b'UIQIIULAsMla7B28+zP7MyvigUuWuWe/MySTufBPtAZ0gUfgGTiTtdpaAQ6BMRACoZECpsCR'
    b'eLzUAYYK/GlUgAp6BXargFvAZRE4I2gAbOSBDXAKBAKeGpiVgataAOfCSuladj03MKkI1gGh'
    b'sFL6wA8amuhkvdmvVVgp2eZNhaAJcK/evVPPzoAGsAe85wQtTAQO1I4PgKUyAVarQA+YSdBc'
    b'4C9EOw+l1xOvi1PYaAF91bfVl15ZjrshaitPO8fnHeDlaRSYa+tPA57kc7MGbyvBiukY99Gz'
    b'cv0GsSMtrJQMcMLPn2cE7APNnICmeEayHggj87KzWkdd18ADsJMRsA3cqrUrCq7rpGIDB7hw'
    b'PA/F66XUyFQ1lp73yNSyQ/9LqssvDf2klqVK6xvhrdNKp5HWMwAAAABJRU5ErkJggg==')

boxtop24_disabled = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA'
    b'AAJ3SURBVEiJvZXBaxNBFIe/N931IIrEIHgQvCi0VC96ananUDyoFOutV9GL0IO0ghVEUFEE'
    b'FbWVIvSo+AdoRcSLgd0suQSlYGlBEAQhomgQKwVN9nnopiTbtCYV/Z2Wmbff92ZZ5sE/jrRT'
    b'FATBDmPMBWBIRLpUdSaO46v9/f2f/0owNze3qVKpnAEuAtsa91R1SVUvZ7PZid7e3p8dC6Io'
    b'Og7cUtW9CXBRRLa0KC0bY0ZyudzjtgTFYrGnVqvdBo4mS4tAK3A6r1X1pLV2tqVAVSWKopvA'
    b'GNAFLImIo6puG/AVjIg8yOVyp0REmwRhGBZExBORWFV/AFs7AKOqJFBR1cha6wOYeoExpgcg'
    b'jmPTKVxE3gMf6w3XWU0CVd2eFM+mAevkO7CgqrtFZKeqzjeymgT1eJ53QFVPAJ/WASuwAGwG'
    b'uoGvqjpaLpf3pwtXCUQkttY+VNVuEZkEftXXk+4+sPxndQOxiEyq6h5r7eTw8HAtzXPWatFa'
    b'WwFGi8XidLVavQscTkS7EtELx3HG+vr65tc56dqCehLAkTAMj4nITAIfstY+/dO70OITrZVG'
    b'YLvwjgQbzX8VvAMIgsDbKKxQKPiNrLTgEYAxJh9F0UQYhpl2wWEYZqIomgBeNrJg9WV3AzjL'
    b'8mX3RVUvVavV6YGBgWrSoQL4vi8A+XzecRzntIhcAbJADbjjed75+mW3cgIRUd/3x40x+4Dn'
    b'QFZEplzXfRNF0WC66yAIDrmu+0pEphJ4XlUP+r4/Xoc3nSCd9MABngGD6WcReQuc8zzvSSvO'
    b'hkcm8A24lslk7m1oZDamYeiPJEv34zi+3s7Q7yilUsktlUqdTDh+A7n9DCIk8XerAAAAAElF'
    b'TkSuQmCC')

