#----------------------------------------------------------------------
# This file was generated by C:\Program Files\Python37\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

folder24 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA'
    b'AACVSURBVEiJ7ZVBCoMwEEUfXVhvJBi8XqteTHqQxEsU2kUTSDUSp6aCkg+fgQT+m8liAmfR'
    b'FegBA7wCfgDlFkC/EOy73QJwndeBuwp4Wle/AlyXS2qJT+hsgA4oJIASGASQ2ZPGABIpm6X/'
    b'BfjKuyQMDSoDMiADdgSMtqoEmY2txj+UrOO1vvmAgs8O1wmCNXBn8h8cV2/NrWNSPN5NnAAA'
    b'AABJRU5ErkJggg==')

