#----------------------------------------------------------------------
# This file was generated by C:\Program Files\Python37\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

maximize = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA'
    b'AACLSURBVEiJ7ZVLCoAwDEQfInonP+dT8Vj1Kq3H0E0KKqGCrQulA6GFTN90lcCfVAMz4IDt'
    b'UCbwxly8DpiASjNPF/OTAF+jZvY/bwLAO3XCsFrTp8fqxCkSAIN6PaA83JdEzFScrCxFhvDc'
    b'iebkUXEbsMrZRvB6OZ3WHEm3cAbNXEmIjQiwAldX5je1AzHLQQnGNksrAAAAAElFTkSuQmCC')

