#----------------------------------------------------------------------
# This file was generated by C:\Program Files\Python37\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

maximize24 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA'
    b'AACLSURBVEiJ7ZVLCoAwDEQfInonP+dT8Vj1Kq3H0E0KKqGCrQulA6GFTN90lcCfVAMz4IDt'
    b'UCbwxly8DpiASjNPF/OTAF+jZvY/bwLAO3XCsFrTp8fqxCkSAIN6PaA83JdEzFScrCxFhvDc'
    b'iebkUXEbsMrZRvB6OZ3WHEm3cAbNXEmIjQiwAldX5je1AzHLQQnGNksrAAAAAElFTkSuQmCC')

maximize24_disabled = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA'
    b'AAD9SURBVEiJ7ZVBTsMwEEWfrUqsEiXZBY6QG6TDSRC3QMAGKiFOEu6QAySjHiXdes3GbGrk'
    b'QLtIGiQq9a1G45n/bVkew7ljQtC27VWapu/AHVBGNSoit4eaVbUHJErtvPcfRVG8VFX1CbAK'
    b'K0mSvAEPJ264NMY8Ouc88Dw6gaoOQGmtXdd1vZ2jrqoC9MAgIjcANnYHmCsOICK6D69Dzh6p'
    b'XYw/N1hFsR6tmsZSOhcu/ERV+/3wWlQnfgdyoH4OI53zHxWxwQ6g67r1XDFVDR/TEHLfd2CM'
    b'abz3T9ZaVR2Nkyk/WqD5ZZBl2atzDu/9PdE8n8gANHmeb2b2/0O+ABn8TUgJVS+QAAAAAElF'
    b'TkSuQmCC')

