#----------------------------------------------------------------------
# This file was generated by C:\Program Files\Python37\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

play24 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA'
    b'AAC/SURBVEiJ3dWhqkJBEMbxn8dgusVgtthMVp9AzL6Cr+Ar2E2+gk9gFERst9wn0HjDDYJB'
    b'QY7BPXAw3bCD6AfLMjvD/GF3Z4ZP1BY/GEYByrRuWOArCnBJ+xHjCEAf+5q9QicnAApMcUpn'
    b'f8lu5AJU6mJd823QywmoNMFv8p8xQzMnANpY1uK+McgJqDTCIcVeMUcrJ4BHjSw8aqbE7jmg'
    b'+GeirHr5FYU+ctg37QoqtNBWEd7swtt12MAJH5nvpTvvwl6shFAYTgAAAABJRU5ErkJggg==')

