#----------------------------------------------------------------------
# This file was generated by C:\Program Files\Python37\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

settings24 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA'
    b'AAIxSURBVEiJndVLS1VRFAfwnw8yaqLQpHwUzpsqFPgRJGmSYfQaFDRNmvSgSaWTghxFhQ20'
    b'aYU2aGzDkPwAUdI1AoNAnJR5G+x1uttzr3rzD4tz9nrttddea22aQwcmsRI0gX1N2jaFSVRL'
    b'9GCvzrowhL6MtxJOT+Bk/Fcy+SBGcGQ356NYCwebmMJwA4efg3cZb9VOtY4z2znvDoVNLMR/'
    b'npKJTPdmSfYNc2G7Flmow0goz8W6H8/wGjfQUtK/gGncQWfwFsLHUKMNBrNoOhsp7IJ+6dR/'
    b'0Lud0nxscncPGzwP28c5s7Wk9DK+fSV+T8hWpMueDV6OQ/F9V965DeNYwkZEcS2T92JVfR+s'
    b'ljYZz2RbmvF2JviBh2gvnaoqlWNPUFGas5lei9R8FaVmXI7FcMlxgcIgv7he9b2R418ztmJ/'
    b'MD9JKdoO1R1kZWy526kw/o1FKZc5ZtVS1BtUpGimpHtLrcuruAcH8dTWzr2aGfVo7pIvZrIK'
    b'7itN3HacC4VXpch64iSVoBn1ZTodtpfKTgtsSN1MqqYcX3HWzliO72mp6epwVBpW61Lb/y86'
    b'pTFTxUDBzG/7mFTLi1JFdUoj4wXON3B4BW8i2n78xIeQdTeKoEsatZvSRC2iKehRpjtekq3j'
    b'vVoGDm93zFFbq2keY/gV1BF6H0M+JpX5ZqzX7PDgFDgivQ0DGW8pHJzCcaln1tWKpE96A/Yy'
    b'5sF19X3wZK/OGqFNeia/4Ls08w80Y/gX6KK9ZYZNWiIAAAAASUVORK5CYII=')

